import { LucideIcon } from 'lucide-react'
import {
  LayoutDashboard,
  User,
  Users,
  Shield,
  Menu,
  Settings,
  Home,
  File,
  Folder,
  Grid3X3,
  Store,
  ShoppingBag,
  ShoppingCart,
  BarChart3,
  PieChart,
  LineChart,
  Table,
  Database,
  Cloud,
  Code,
  Bug,
  Wrench,
  Bell,
  MessageSquare,
  Mail,
  Phone,
  Camera,
  Image,
  Video,
  FileText,
  FileSpreadsheet,
  FolderOpen,
  Inbox,
  Paperclip,
  Link,
  Globe,
  Wifi,
  Lock,
  Unlock,
  Key,
  ShieldCheck,
  Flame,
  Zap,
  Rocket,
  Star,
  Heart,
  ThumbsUp,
  ThumbsDown,
  Eye,
  EyeOff,
  Search,
  Filter,
  ArrowUpAZ,
  ArrowDownAZ,
  RefreshCw,
  Download,
  Upload,
  Printer,
  Copy,
  Scissors,
  Trash2,
  Pencil,
  Plus,
  Minus,
  X,
  Check,
  XCircle,
  CheckCircle,
  AlertCircle,
  Info,
  HelpCircle,
  AlertTriangle,
  Ban,
  PlayCircle,
  PauseCircle,
  SkipBack,
  SkipForward,
  Rewind,
  FastForward,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  ChevronsLeft,
  ChevronsRight,
  CornerDownLeft,
  Repeat,
  RotateCcw,
  Undo,
  Redo,
  LogIn,
  LogOut,
  UserPlus,
  UserMinus,
  UserCog,
  ClipboardList,
  Compass,
  Building2,
  GitBranch,
  Workflow,
  ListTodo,
} from 'lucide-react'

// 图标映射表 - Lucide Icons
export const iconMap: Record<string, LucideIcon> = {
  // 常用
  DashboardOutlined: LayoutDashboard,
  UserOutlined: User,
  TeamOutlined: Users,
  SafetyOutlined: Shield,
  MenuOutlined: Menu,
  SettingOutlined: Settings,
  HomeOutlined: Home,
  FileOutlined: File,
  FolderOutlined: Folder,
  AppstoreOutlined: Grid3X3,
  ShopOutlined: Store,
  ShoppingOutlined: ShoppingBag,
  ShoppingCartOutlined: ShoppingCart,
  // 数据
  BarChartOutlined: BarChart3,
  PieChartOutlined: PieChart,
  LineChartOutlined: LineChart,
  TableOutlined: Table,
  DatabaseOutlined: Database,
  CloudOutlined: Cloud,
  ApiOutlined: Code,
  CodeOutlined: Code,
  BugOutlined: Bug,
  ToolOutlined: Wrench,
  // 通知
  BellOutlined: Bell,
  MessageOutlined: MessageSquare,
  MailOutlined: Mail,
  PhoneOutlined: Phone,
  // 媒体
  CameraOutlined: Camera,
  PictureOutlined: Image,
  VideoCameraOutlined: Video,
  // 文件
  FileTextOutlined: FileText,
  FileExcelOutlined: FileSpreadsheet,
  FolderOpenOutlined: FolderOpen,
  InboxOutlined: Inbox,
  PaperClipOutlined: Paperclip,
  LinkOutlined: Link,
  // 网络
  GlobalOutlined: Globe,
  WifiOutlined: Wifi,
  // 安全
  LockOutlined: Lock,
  UnlockOutlined: Unlock,
  KeyOutlined: Key,
  SafetyCertificateOutlined: ShieldCheck,
  // 状态
  FireOutlined: Flame,
  ThunderboltOutlined: Zap,
  RocketOutlined: Rocket,
  StarOutlined: Star,
  HeartOutlined: Heart,
  LikeOutlined: ThumbsUp,
  DislikeOutlined: ThumbsDown,
  EyeOutlined: Eye,
  EyeInvisibleOutlined: EyeOff,
  // 操作
  SearchOutlined: Search,
  FilterOutlined: Filter,
  SortAscendingOutlined: ArrowUpAZ,
  SortDescendingOutlined: ArrowDownAZ,
  ReloadOutlined: RefreshCw,
  SyncOutlined: RefreshCw,
  DownloadOutlined: Download,
  UploadOutlined: Upload,
  PrinterOutlined: Printer,
  CopyOutlined: Copy,
  ScissorOutlined: Scissors,
  DeleteOutlined: Trash2,
  EditOutlined: Pencil,
  PlusOutlined: Plus,
  MinusOutlined: Minus,
  CloseOutlined: X,
  CheckOutlined: Check,
  CloseCircleOutlined: XCircle,
  CheckCircleOutlined: CheckCircle,
  ExclamationCircleOutlined: AlertCircle,
  InfoCircleOutlined: Info,
  QuestionCircleOutlined: HelpCircle,
  WarningOutlined: AlertTriangle,
  StopOutlined: Ban,
  // 播放
  PlayCircleOutlined: PlayCircle,
  PauseCircleOutlined: PauseCircle,
  StepBackwardOutlined: SkipBack,
  StepForwardOutlined: SkipForward,
  FastBackwardOutlined: Rewind,
  FastForwardOutlined: FastForward,
  // 方向
  LeftOutlined: ChevronLeft,
  RightOutlined: ChevronRight,
  UpOutlined: ChevronUp,
  DownOutlined: ChevronDown,
  ArrowLeftOutlined: ArrowLeft,
  ArrowRightOutlined: ArrowRight,
  ArrowUpOutlined: ArrowUp,
  ArrowDownOutlined: ArrowDown,
  DoubleLeftOutlined: ChevronsLeft,
  DoubleRightOutlined: ChevronsRight,
  EnterOutlined: CornerDownLeft,
  RetweetOutlined: Repeat,
  RollbackOutlined: RotateCcw,
  UndoOutlined: Undo,
  RedoOutlined: Redo,
  // 用户
  LoginOutlined: LogIn,
  LogoutOutlined: LogOut,
  UserAddOutlined: UserPlus,
  UserDeleteOutlined: UserMinus,
  UsergroupAddOutlined: UserCog,
  // 工单相关
  ClipboardListOutlined: ClipboardList,
  CompassOutlined: Compass,
  BankOutlined: Building2,
  ApartmentOutlined: GitBranch,
  WorkflowOutlined: Workflow,
  ListTodoOutlined: ListTodo,
}

// 图标列表
export const iconList = Object.keys(iconMap)

// 图标分类
export const iconCategories = {
  常用: [
    'DashboardOutlined',
    'UserOutlined',
    'TeamOutlined',
    'SafetyOutlined',
    'MenuOutlined',
    'SettingOutlined',
    'HomeOutlined',
    'FileOutlined',
    'FolderOutlined',
  ],
  数据: [
    'BarChartOutlined',
    'PieChartOutlined',
    'LineChartOutlined',
    'TableOutlined',
    'DatabaseOutlined',
  ],
  操作: [
    'EditOutlined',
    'DeleteOutlined',
    'PlusOutlined',
    'MinusOutlined',
    'CopyOutlined',
    'SearchOutlined',
    'FilterOutlined',
    'ReloadOutlined',
    'SyncOutlined',
  ],
  文件: [
    'FileTextOutlined',
    'FileExcelOutlined',
    'FolderOpenOutlined',
    'InboxOutlined',
    'PaperClipOutlined',
  ],
  导航: [
    'LeftOutlined',
    'RightOutlined',
    'UpOutlined',
    'DownOutlined',
    'ArrowLeftOutlined',
    'ArrowRightOutlined',
    'ArrowUpOutlined',
    'ArrowDownOutlined',
  ],
  状态: [
    'CheckOutlined',
    'CloseOutlined',
    'CheckCircleOutlined',
    'CloseCircleOutlined',
    'ExclamationCircleOutlined',
    'InfoCircleOutlined',
    'QuestionCircleOutlined',
    'WarningOutlined',
  ],
  用户: [
    'UserAddOutlined',
    'UserDeleteOutlined',
    'LoginOutlined',
    'LogoutOutlined',
  ],
  其他: [
    'AppstoreOutlined',
    'ShopOutlined',
    'ShoppingOutlined',
    'ShoppingCartOutlined',
    'CloudOutlined',
    'ApiOutlined',
    'CodeOutlined',
    'ToolOutlined',
    'BellOutlined',
    'MessageOutlined',
    'MailOutlined',
    'PhoneOutlined',
    'GlobalOutlined',
    'WifiOutlined',
    'LockOutlined',
    'UnlockOutlined',
    'KeyOutlined',
    'SafetyCertificateOutlined',
  ],
}
